title: Indexmod
email: indexmod@me.com
description: > # многострочное значение
  Editor in the GQ editorial in Moscow, as well as I have got a chance to experiment
  at the Department of New Media of MSU. Since then, I became interested in visual
  design and creating of art objects such as eco-hotel-capsule, interior robots,
  and other multimedia creatures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://indexmod.xyz"

github_username: indexmod

# Build settings
plugins:
  - jekyll-feed

css:
  - "/assets/css/main.css"
