title: Indexmod Fashion & Art Сhainpædia
email: indexmod@me.com
description: > # многострочное значение
  Editor Andr-o-Dei indexmod@me.com
url: ""        # ← пусто (ВАЖНО)
baseurl: "/indexmod"

github_username: indexmod

plugins:
  - jekyll-feed
  - jekyll-relative-links



css:
  - "/assets/css/main.css"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
